from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Live_feed(object):
    def setupUi(self, Live_feed, switch_handler=None):
        Live_feed.setObjectName("Live_feed")
        Live_feed.resize(2406, 813)  # Scaled by 1.6 horizontally and 1.5 vertically

        scale_x = 1.6
        scale_y = 1.5

        self.centralwidget = QtWidgets.QWidget(parent=Live_feed)
        self.centralwidget.setObjectName("centralwidget")
        self.Screenshot = QtWidgets.QLabel(parent=self.centralwidget)
        self.Screenshot.setGeometry(QtCore.QRect(int(600 * scale_x), int(200 * scale_y), int(371 * scale_x), int(121 * scale_y)))
        self.Screenshot.setObjectName("Screenshot")
        self.Webcam = QtWidgets.QLabel(parent=self.centralwidget)
        self.Webcam.setGeometry(QtCore.QRect(int(0 * scale_x), int(0 * scale_y), int(500 * scale_x), int(400 * scale_y)))
        self.Webcam.setObjectName("Webcam")
        self.Webcam_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Webcam_button.setGeometry(QtCore.QRect(int(200 * scale_x), int(291 * scale_y), int(51 * scale_x), int(41 * scale_y)))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/web3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Webcam_button.setIcon(icon)
        self.Webcam_button.setIconSize(QtCore.QSize(int(50 * scale_x), int(55 * scale_y)))
        self.Webcam_button.setObjectName("Webcam_button")
        self.Screenshot_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Screenshot_button.setGeometry(QtCore.QRect(int(260 * scale_x), int(291 * scale_y), int(51 * scale_x), int(41 * scale_y)))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Screenshot.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Screenshot_button.setIcon(icon1)
        self.Screenshot_button.setIconSize(QtCore.QSize(int(50 * scale_x), int(60 * scale_y)))
        self.Screenshot_button.setObjectName("Screenshot_button")
        self.switch_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked=switch_handler)
        self.switch_button.setGeometry(QtCore.QRect(int(140 * scale_x), int(340 * scale_y), int(251 * scale_x), int(35 * scale_y)))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.switch_button.setFont(font)
        self.switch_button.setObjectName("switch_button")
        self.Forward = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Forward.setGeometry(QtCore.QRect(int(58 * scale_x), int(270 * scale_y), int(27 * scale_x), int(27 * scale_y)))
        self.Forward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Arrow_up.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Forward.setIcon(icon2)
        self.Forward.setIconSize(QtCore.QSize(int(27 * scale_x), int(27 * scale_y)))
        self.Forward.setObjectName("Forward")
        self.Right = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Right.setGeometry(QtCore.QRect(int(100 * scale_x), int(307 * scale_y), int(27 * scale_x), int(27 * scale_y)))
        self.Right.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.Right.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Right.setIcon(icon3)
        self.Right.setIconSize(QtCore.QSize(int(27 * scale_x), int(27 * scale_y)))
        self.Right.setShortcut("")
        self.Right.setObjectName("Right")
        self.Reverse = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Reverse.setGeometry(QtCore.QRect(int(58 * scale_x), int(344 * scale_y), int(27 * scale_x), int(27 * scale_y)))
        self.Reverse.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Arrow_down.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Reverse.setIcon(icon4)
        self.Reverse.setIconSize(QtCore.QSize(int(27 * scale_x), int(27 * scale_y)))
        self.Reverse.setObjectName("Reverse")
        self.Left = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Left.setGeometry(QtCore.QRect(int(16 * scale_x), int(307 * scale_y), int(27 * scale_x), int(27 * scale_y)))
        self.Left.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Arrow_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Left.setIcon(icon5)
        self.Left.setIconSize(QtCore.QSize(int(27 * scale_x), int(27 * scale_y)))
        self.Left.setObjectName("Left")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(int(150 * scale_x), int(270 * scale_y), int(191 * scale_x), int(61 * scale_y)))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(int(49 * scale_x), int(298 * scale_y), int(45 * scale_x), int(45 * scale_y)))
        self.Stop.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Center.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Stop.setIcon(icon6)
        self.Stop.setIconSize(QtCore.QSize(int(45 * scale_x), int(45 * scale_y)))
        self.Stop.setObjectName("Stop")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(int(40 * scale_x), int(30 * scale_y), int(51 * scale_x), int(21 * scale_y)))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Strong.JPG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(int(40 * scale_x), int(30 * scale_y), int(51 * scale_x), int(21 * scale_y)))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Weak.JPG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.Decelerate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Decelerate.setGeometry(QtCore.QRect(int(92 * scale_x), int(255 * scale_y), int(41 * scale_x), int(41 * scale_y)))
        self.Decelerate.setObjectName("Decelerate")
        self.Accelerate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Accelerate.setGeometry(QtCore.QRect(int(10 * scale_x), int(255 * scale_y), int(41 * scale_x), int(41 * scale_y)))
        self.Accelerate.setObjectName("Accelerate")
        self.lineSpeed = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineSpeed.setGeometry(QtCore.QRect(int(440 * scale_x), int(310 * scale_y), int(41 * scale_x), int(20 * scale_y)))
        self.lineSpeed.setObjectName("lineSpeed")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(int(440 * scale_x), int(332 * scale_y), int(41 * scale_x), int(20 * scale_y)))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(int(440 * scale_x), int(354 * scale_y), int(41 * scale_x), int(20 * scale_y)))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.Speed = QtWidgets.QLabel(parent=self.centralwidget)
        self.Speed.setGeometry(QtCore.QRect(int(398 * scale_x), int(316 * scale_y), int(21 * scale_x), int(10 * scale_y)))
        self.Speed.setWordWrap(True)
        self.Speed.setObjectName("Speed")
        self.Voltage = QtWidgets.QLabel(parent=self.centralwidget)
        self.Voltage.setGeometry(QtCore.QRect(int(397 * scale_x), int(338 * scale_y), int(35 * scale_x), int(10 * scale_y)))
        self.Voltage.setObjectName("Voltage")
        self.Current = QtWidgets.QLabel(parent=self.centralwidget)
        self.Current.setGeometry(QtCore.QRect(int(397 * scale_x), int(355 * scale_y), int(41 * scale_x), int(20 * scale_y)))
        self.Current.setScaledContents(False)
        self.Current.setObjectName("Current")

        self.Screenshot.raise_()
        self.Webcam.raise_()
        self.switch_button.raise_()
        self.label_2.raise_()
        self.Reverse.raise_()
        self.Left.raise_()
        self.Forward.raise_()
        self.Right.raise_()
        self.Stop.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.Decelerate.raise_()
        self.Accelerate.raise_()
        self.lineSpeed.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.Speed.raise_()
        self.Voltage.raise_()
        self.Current.raise_()
        self.Webcam_button.raise_()
        self.Screenshot_button.raise_()

        self.retranslateUi(Live_feed)
        QtCore.QMetaObject.connectSlotsByName(Live_feed)

    def retranslateUi(self, Live_feed):
        _translate = QtCore.QCoreApplication.translate
        Live_feed.setWindowTitle(_translate("Live_feed", "Live_feed"))
        self.switch_button.setText(_translate("Live_feed", "Switch Mode"))
        self.Decelerate.setText(_translate("Live_feed", "Decelerate"))
        self.Accelerate.setText(_translate("Live_feed", "Accelerate"))
        self.Speed.setText(_translate("Live_feed", "Speed"))
        self.Voltage.setText(_translate("Live_feed", "Voltage/V"))
        self.Current.setText(_translate("Live_feed", "Current/mA"))
